import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import { SidebarConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';

const mainSidebar = <SidebarConfig>[
  {
    type: 'category',
    label: '۰. مقدمه و راهنما',
    items: [{type: 'autogenerated', dirName: '00-intro'}],
  },
  {
    type: 'category',
    label: '۱. شروع کار در تیم',
    items: [{type: 'autogenerated', dirName: '01-onboarding'}],
  },
  {
    type: 'category',
    label: '۲. مفاهیم پایه و پیش‌نیازها',
    items: [{type: 'autogenerated', dirName: '02-basics'}],
  },
  {
    type: 'category',
    label: '۳. همکاری و کنترل نسخه',
    items: [{type: 'autogenerated', dirName: '03-collaboration'}],
  },
  {
    type: 'category',
    label: '۴. DevOps و زیرساخت',
    items: [{type: 'autogenerated', dirName: '04-devops'}],
  },
  {
    type: 'category',
    label: '۵. معماری‌ها و طراحی سیستم',
    items: [{type: 'autogenerated', dirName: '05-architecture'}],
  },
  {
    type: 'category',
    label: '۶. فرآیندها و گردش کار تیم',
    items: [{type: 'autogenerated', dirName: '06-processes'}],
  },
  {
    type: 'category',
    label: '۷. راهنماهای عملی',
    items: [{type: 'autogenerated', dirName: '07-guides'}],
  },
  {
    type: 'category',
    label: '۸. خطاهای رایج و رفع اشکال',
    items: [{type: 'autogenerated', dirName: '08-runbooks'}],
  },
  {
    type: 'category',
    label: '۹. ابزارهای کمکی توسعه',
    items: [{type: 'autogenerated', dirName: '09-devtools'}],
  },
  {
    type: 'category',
    label: '۱۰. منابع و مطالعه بیشتر',
    items: [{type: 'autogenerated', dirName: '10-resources'}],
  },
  {
    type: 'category',
    label: 'تمپلیت‌ها',
    items: [{type: 'autogenerated', dirName: 'templates'}],
  },
];

const sidebars: SidebarsConfig = {
  // برای سازگاری با تنظیمات پیش‌فرض داکیوسورَس
  tutorialSidebar: mainSidebar,

  // اگر جایی خواستی به صورت صریح از این سایدبار استفاده کنی
  docsSidebar: mainSidebar,
};

export default sidebars;

