import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docsSidebar: [
    {
      type: 'category',
      label: 'مستندات آموزش ابزارها و نرم‌افزارها',
      items: [
        'tools-software/tools-software',
        {
          type: 'category',
          label: 'Docker',
          items: [
            'tools-software/docker/docker-introduction',
            'tools-software/docker/docker-installation',
            'tools-software/docker/docker-core-concepts',
            'tools-software/docker/docker-commands',
            'tools-software/docker/dockerfile',
            'tools-software/docker/docker-compose',
            'tools-software/docker/docker-best-practices',
          ],
        },
        {
          type: 'category',
          label: 'Git',
          items: [
            'tools-software/git/git-introduction',
            'tools-software/git/git-installation',
            'tools-software/git/git-core-concepts',
            'tools-software/git/git-essential-commands',
            'tools-software/git/git-branch-management',
            'tools-software/git/git-remote-workflow',
            'tools-software/git/git-merge-conflicts',
          ],
        },
        {
          type: 'category',
          label: 'GitHub',
          items: [
            'tools-software/github/github-introduction',
            'tools-software/github/github-create-repo',
            'tools-software/github/github-issues-pr',
            'tools-software/github/github-actions',
            'tools-software/github/github-security-teams',
            'tools-software/github/github-releases',
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'مستندات معماری‌های نرم‌افزاری',
      items: [
        'architecture/architecture-architectures',
        {
          type: 'category',
          label: 'Microservice Architecture',
          items: [
            'architecture/microservice/microservice-introduction',
            'architecture/microservice/microservice-pros-cons',
            'architecture/microservice/microservice-patterns',
            'architecture/microservice/microservice-communication',
            'architecture/microservice/microservice-monitoring',
            'architecture/microservice/microservice-tools',
          ],
        },
        {
          type: 'category',
          label: 'Modular Architecture',
          items: [
            'architecture/modular/modular-introduction',
            'architecture/modular/modular-benefits-use-cases',
            'architecture/modular/modular-structure',
            'architecture/modular/modular-communication',
            'architecture/modular/modular-patterns',
          ],
        },
        {
          type: 'category',
          label: 'MVC Architecture',
          items: [
            'architecture/mvc/mvc-introduction',
            'architecture/mvc/mvc-separation',
            'architecture/mvc/mvc-request-cycle',
            'architecture/mvc/mvc-framework-examples',
            'architecture/mvc/mvc-best-practices',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
